Repository sebascm/faker, pull requests merged in 2019-11, with the labels that each got.

#8 config/dependencies_jenkins
  Jenkinsfile
Labels: configuration

#9 config/benchmark jenkins
  Jenkinsfile
  tests/benchmarks/benchmark.sh
Labels: configuration

#10 enhancement/mail report
  Jenkinsfile
Labels: configuration, enhancement

#12 enhancement/mail_success
  Jenkinsfile
Labels: configuration, enhancement

#14 Enhancement/refactor artifact
  Jenkinsfile
Labels: enhancement

#15 enhancement/automatic_merge
  Jenkinsfile
Labels: configuration, enhancement
